openapi: 3.0.3
info:
  contact:
    email: contact@immutable.com
    name: Support
    url: https://immutable.com
  description: running ts sdk as an api
  title: TS SDK API
  version: 1.0.0
servers:
- description: Production Server
  url: https://api.immutable.com
- description: Sandbox Server
  url: https://api.sandbox.immutable.com
tags:
- name: ts sdk api
paths:
  /v1/heartbeat:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_v1_heartbeat_get_200_response'
          description: heartbeat
    head:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_v1_heartbeat_get_200_response'
          description: heartbeat
  /v1/ts-sdk/orderbook/cancelOrders:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_v1_ts_sdk_orderbook_cancelOrders_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_v1_ts_sdk_orderbook_cancelOrders_post_200_response'
          description: Response schema for the cancelOrder endpoint
  /v1/ts-sdk/orderbook/cancelOrdersOnChain:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_v1_ts_sdk_orderbook_cancelOrdersOnChain_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_v1_ts_sdk_orderbook_cancelOrdersOnChain_post_200_response'
          description: Response schema for the cancelOrder endpoint
  /v1/ts-sdk/orderbook/createListing:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_v1_ts_sdk_orderbook_createListing_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_v1_ts_sdk_orderbook_createListing_post_200_response'
          description: The response schema for the create listing endpoint
  /v1/ts-sdk/orderbook/fulfillOrder:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_v1_ts_sdk_orderbook_fulfillOrder_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_v1_ts_sdk_orderbook_fulfillOrder_post_200_response'
          description: Response schema for the fulfillOrder endpoint
  /v1/ts-sdk/orderbook/prepareListing:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_v1_ts_sdk_orderbook_prepareListing_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_v1_ts_sdk_orderbook_prepareListing_post_200_response'
          description: Response schema for the prepareListing endpoint
  /v1/ts-sdk/orderbook/prepareOrderCancellations:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_v1_ts_sdk_orderbook_prepareOrderCancellations_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_v1_ts_sdk_orderbook_prepareOrderCancellations_post_200_response'
          description: Response schema for the prepareOrderCancellations endpoint
components:
  schemas:
    ERC1155Item:
      example:
        amount: amount
        tokenId: tokenId
        contractAddress: contractAddress
        type: ERC1155
      properties:
        amount:
          type: string
        contractAddress:
          type: string
        tokenId:
          type: string
        type:
          enum:
          - ERC1155
          type: string
      required:
      - amount
      - contractAddress
      - tokenId
      - type
      type: object
    ERC20Item:
      example:
        amount: amount
        contractAddress: contractAddress
        type: ERC20
      properties:
        amount:
          type: string
        contractAddress:
          type: string
        type:
          enum:
          - ERC20
          type: string
      required:
      - amount
      - contractAddress
      - type
      type: object
    ERC721Item:
      properties:
        contractAddress:
          type: string
        tokenId:
          type: string
        type:
          enum:
          - ERC721
          type: string
      required:
      - contractAddress
      - tokenId
      - type
      type: object
    NativeItem:
      properties:
        amount:
          type: string
        type:
          enum:
          - NATIVE
          type: string
      required:
      - amount
      - type
      type: object
    Action:
      oneOf:
      - $ref: '#/components/schemas/TransactionAction'
      - $ref: '#/components/schemas/SignableAction'
    BigNumber:
      type: string
    BytesLike:
      type: string
    ItemType:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      type: number
    OrderComponents:
      example:
        offer:
        - itemType: null
          startAmount: startAmount
          identifierOrCriteria: identifierOrCriteria
          endAmount: endAmount
          token: token
        - itemType: null
          startAmount: startAmount
          identifierOrCriteria: identifierOrCriteria
          endAmount: endAmount
          token: token
        orderType: 6.027456183070403
        salt: salt
        zoneHash: zoneHash
        zone: zone
        conduitKey: conduitKey
        offerer: offerer
        consideration:
        - itemType: 0.8008281904610115
          startAmount: startAmount
          identifierOrCriteria: identifierOrCriteria
          recipient: recipient
          endAmount: endAmount
          token: token
        - itemType: 0.8008281904610115
          startAmount: startAmount
          identifierOrCriteria: identifierOrCriteria
          recipient: recipient
          endAmount: endAmount
          token: token
        startTime: startTime
        endTime: endTime
        totalOriginalConsiderationItems: totalOriginalConsiderationItems
        counter: counter
      properties:
        conduitKey:
          type: string
        consideration:
          items:
            $ref: '#/components/schemas/OrderComponents_consideration_inner'
          type: array
        endTime:
          type: string
        offer:
          items:
            $ref: '#/components/schemas/OrderComponents_offer_inner'
          type: array
        offerer:
          type: string
        orderType:
          $ref: '#/components/schemas/OrderType'
        salt:
          type: string
        startTime:
          type: string
        totalOriginalConsiderationItems:
          type: string
        zone:
          type: string
        zoneHash:
          type: string
        counter:
          type: string
      required:
      - conduitKey
      - consideration
      - counter
      - endTime
      - offer
      - offerer
      - orderType
      - salt
      - startTime
      - totalOriginalConsiderationItems
      - zone
      - zoneHash
      type: object
    OrderType:
      enum:
      - 0
      - 1
      - 2
      - 3
      type: number
    RecordStringTypedDataField:
      additionalProperties:
        items:
          $ref: '#/components/schemas/RecordStringTypedDataField_value_inner'
        type: array
      type: object
    RecordStringAny:
      additionalProperties: true
      type: object
    SignableAction:
      example:
        purpose: CREATE_LISTING
        message:
          types:
            key:
            - name: name
              type: type
            - name: name
              type: type
          primaryType: primaryType
          domain:
            salt: salt
            chainId: chainId
            name: name
            version: version
            verifyingContract: verifyingContract
          message:
            key: ""
        type: SIGNABLE
      properties:
        message:
          $ref: '#/components/schemas/SignableAction_message'
        purpose:
          $ref: '#/components/schemas/SignablePurpose'
        type:
          enum:
          - SIGNABLE
          type: string
      required:
      - type
      type: object
    SignablePurpose:
      enum:
      - CREATE_LISTING
      - OFF_CHAIN_CANCELLATION
      type: string
    TransactionAction:
      example:
        populatedTransactions:
          data: data
          accessList:
          - address: address
            storageKeys:
            - storageKeys
            - storageKeys
          - address: address
            storageKeys:
            - storageKeys
            - storageKeys
          customData:
            key: ""
          type: 1.4658129805029452
          nonce: 0.8008281904610115
          gasLimit: gasLimit
          chainId: 6.027456183070403
          maxPriorityFeePerGas: maxPriorityFeePerGas
          from: from
          to: to
          maxFeePerGas: maxFeePerGas
          value: value
          gasPrice: gasPrice
          ccipReadEnabled: true
        purpose: APPROVAL
        type: TRANSACTION
      properties:
        populatedTransactions:
          $ref: '#/components/schemas/TransactionAction_populatedTransactions'
        purpose:
          $ref: '#/components/schemas/TransactionPurpose'
        type:
          enum:
          - TRANSACTION
          type: string
      required:
      - type
      type: object
    TransactionPurpose:
      enum:
      - APPROVAL
      - FULFILL_ORDER
      - CANCEL
      type: string
    TypedDataDomain:
      example:
        salt: salt
        chainId: chainId
        name: name
        version: version
        verifyingContract: verifyingContract
      properties:
        chainId:
          type: string
        name:
          type: string
        salt:
          type: string
        verifyingContract:
          type: string
        version:
          type: string
      type: object
    BigNumberish:
      description: Any type that can be used where a big number is needed.
      oneOf:
      - type: string
      - type: number
    FeeValue:
      properties:
        amount:
          type: string
        recipientAddress:
          type: string
      required:
      - amount
      - recipientAddress
      type: object
    CancellationType:
      description: Whether the cancellation was done on-chain or off-chain or as a
        result of an underfunded account
      enum:
      - ON_CHAIN
      - OFF_CHAIN
      - UNDERFUNDED
      type: string
    Fee:
      example:
        amount: amount
        recipientAddress: recipientAddress
        type: MAKER_ECOSYSTEM
      properties:
        amount:
          type: string
        recipientAddress:
          type: string
        type:
          $ref: '#/components/schemas/FeeType'
      type: object
    FeeType:
      enum:
      - MAKER_ECOSYSTEM
      - TAKER_ECOSYSTEM
      - PROTOCOL
      - ROYALTY
      type: string
    Order:
      example:
        chain:
          name: name
          id: id
        fees:
        - amount: amount
          recipientAddress: recipientAddress
          type: MAKER_ECOSYSTEM
        - amount: amount
          recipientAddress: recipientAddress
          type: MAKER_ECOSYSTEM
        salt: salt
        accountAddress: accountAddress
        signature: signature
        buy:
        - amount: amount
          contractAddress: contractAddress
          type: ERC20
        - amount: amount
          contractAddress: contractAddress
          type: ERC20
        sell:
        - amount: amount
          tokenId: tokenId
          contractAddress: contractAddress
          type: ERC1155
        - amount: amount
          tokenId: tokenId
          contractAddress: contractAddress
          type: ERC1155
        endAt: endAt
        type: LISTING
        createdAt: createdAt
        fillStatus:
          denominator: denominator
          numerator: numerator
        protocolData:
          seaportVersion: seaportVersion
          orderType: FULL_RESTRICTED
          counter: counter
          zoneAddress: zoneAddress
          seaportAddress: seaportAddress
        id: id
        startAt: startAt
        orderHash: orderHash
        status:
          name: ACTIVE
        updatedAt: updatedAt
      properties:
        accountAddress:
          type: string
        buy:
          items:
            $ref: '#/components/schemas/_v1_ts_sdk_orderbook_prepareListing_post_request_buy'
          type: array
        chain:
          $ref: '#/components/schemas/Order_chain'
        createdAt:
          type: string
        endAt:
          description: Time after which the Order is expired
          type: string
        fees:
          items:
            $ref: '#/components/schemas/Fee'
          type: array
        fillStatus:
          $ref: '#/components/schemas/Order_fillStatus'
        id:
          type: string
        orderHash:
          type: string
        protocolData:
          $ref: '#/components/schemas/Order_protocolData'
        salt:
          type: string
        sell:
          items:
            $ref: '#/components/schemas/_v1_ts_sdk_orderbook_prepareListing_post_request_sell'
          type: array
        signature:
          type: string
        startAt:
          description: Time after which the Order is considered active
          type: string
        status:
          $ref: '#/components/schemas/OrderStatus'
        type:
          enum:
          - LISTING
          type: string
        updatedAt:
          type: string
      required:
      - id
      - orderHash
      - sell
      - signature
      - startAt
      - status
      - type
      - updatedAt
      type: object
    OrderStatus:
      description: The Order status
      oneOf:
      - $ref: '#/components/schemas/OrderStatus_oneOf'
      - $ref: '#/components/schemas/OrderStatus_oneOf_1'
      - $ref: '#/components/schemas/OrderStatus_oneOf_2'
      - $ref: '#/components/schemas/OrderStatus_oneOf_3'
      - $ref: '#/components/schemas/OrderStatus_oneOf_4'
      - $ref: '#/components/schemas/OrderStatus_oneOf_5'
    CancelledOrderStatusCancellationType:
      description: Whether the cancellation was done on-chain or off-chain or as a
        result of an underfunded account
      enum:
      - ON_CHAIN
      - OFF_CHAIN
      - UNDERFUNDED
      type: string
    _v1_heartbeat_get_200_response:
      additionalProperties: true
      description: heartbeat
      example:
        status: status
      properties:
        status:
          type: string
      type: object
    _v1_ts_sdk_orderbook_cancelOrders_post_request:
      properties:
        orderIds:
          items:
            type: string
          type: array
        accountAddress:
          type: string
        signature:
          type: string
      required:
      - accountAddress
      - orderIds
      - signature
      type: object
    _v1_ts_sdk_orderbook_cancelOrders_post_200_response_result_failed_cancellations_inner:
      example:
        reason_code: FILLED
        order: order
      properties:
        order:
          description: ID of the order which failed to be cancelled
          type: string
        reason_code:
          description: Reason code indicating why the order failed to be cancelled
          enum:
          - FILLED
          type: string
      type: object
    _v1_ts_sdk_orderbook_cancelOrders_post_200_response_result:
      example:
        failed_cancellations:
        - reason_code: FILLED
          order: order
        - reason_code: FILLED
          order: order
        successful_cancellations:
        - successful_cancellations
        - successful_cancellations
        pending_cancellations:
        - pending_cancellations
        - pending_cancellations
      properties:
        failed_cancellations:
          description: Orders which failed to be cancelled
          items:
            $ref: '#/components/schemas/_v1_ts_sdk_orderbook_cancelOrders_post_200_response_result_failed_cancellations_inner'
          type: array
        pending_cancellations:
          description: Orders which are marked for cancellation but the cancellation
            cannot be guaranteed
          items:
            type: string
          type: array
        successful_cancellations:
          description: Orders which were successfully cancelled
          items:
            type: string
          type: array
      type: object
    _v1_ts_sdk_orderbook_cancelOrders_post_200_response:
      description: Response schema for the cancelOrder endpoint
      example:
        result:
          failed_cancellations:
          - reason_code: FILLED
            order: order
          - reason_code: FILLED
            order: order
          successful_cancellations:
          - successful_cancellations
          - successful_cancellations
          pending_cancellations:
          - pending_cancellations
          - pending_cancellations
      properties:
        result:
          $ref: '#/components/schemas/_v1_ts_sdk_orderbook_cancelOrders_post_200_response_result'
      type: object
    _v1_ts_sdk_orderbook_cancelOrdersOnChain_post_request:
      properties:
        orderIds:
          items:
            type: string
          type: array
        accountAddress:
          type: string
      required:
      - accountAddress
      - orderIds
      type: object
    _v1_ts_sdk_orderbook_cancelOrdersOnChain_post_200_response:
      description: Response schema for the cancelOrder endpoint
      example:
        cancellationAction:
          populatedTransactions:
            data: data
            accessList:
            - address: address
              storageKeys:
              - storageKeys
              - storageKeys
            - address: address
              storageKeys:
              - storageKeys
              - storageKeys
            customData:
              key: ""
            type: 1.4658129805029452
            nonce: 0.8008281904610115
            gasLimit: gasLimit
            chainId: 6.027456183070403
            maxPriorityFeePerGas: maxPriorityFeePerGas
            from: from
            to: to
            maxFeePerGas: maxFeePerGas
            value: value
            gasPrice: gasPrice
            ccipReadEnabled: true
          purpose: APPROVAL
          type: TRANSACTION
      properties:
        cancellationAction:
          $ref: '#/components/schemas/TransactionAction'
      type: object
    _v1_ts_sdk_orderbook_createListing_post_request:
      properties:
        makerFees:
          items:
            $ref: '#/components/schemas/FeeValue'
          type: array
        orderComponents:
          $ref: '#/components/schemas/OrderComponents'
        orderHash:
          type: string
        orderSignature:
          type: string
      required:
      - makerFees
      - orderComponents
      - orderHash
      - orderSignature
      type: object
    _v1_ts_sdk_orderbook_createListing_post_200_response:
      description: The response schema for the create listing endpoint
      example:
        result:
          chain:
            name: name
            id: id
          fees:
          - amount: amount
            recipientAddress: recipientAddress
            type: MAKER_ECOSYSTEM
          - amount: amount
            recipientAddress: recipientAddress
            type: MAKER_ECOSYSTEM
          salt: salt
          accountAddress: accountAddress
          signature: signature
          buy:
          - amount: amount
            contractAddress: contractAddress
            type: ERC20
          - amount: amount
            contractAddress: contractAddress
            type: ERC20
          sell:
          - amount: amount
            tokenId: tokenId
            contractAddress: contractAddress
            type: ERC1155
          - amount: amount
            tokenId: tokenId
            contractAddress: contractAddress
            type: ERC1155
          endAt: endAt
          type: LISTING
          createdAt: createdAt
          fillStatus:
            denominator: denominator
            numerator: numerator
          protocolData:
            seaportVersion: seaportVersion
            orderType: FULL_RESTRICTED
            counter: counter
            zoneAddress: zoneAddress
            seaportAddress: seaportAddress
          id: id
          startAt: startAt
          orderHash: orderHash
          status:
            name: ACTIVE
          updatedAt: updatedAt
      properties:
        result:
          $ref: '#/components/schemas/Order'
      type: object
    _v1_ts_sdk_orderbook_fulfillOrder_post_request_takerFees_inner:
      properties:
        amount:
          type: string
        recipientAddress:
          type: string
      required:
      - amount
      - recipientAddress
      type: object
    _v1_ts_sdk_orderbook_fulfillOrder_post_request:
      properties:
        listingId:
          description: listingId
          type: string
        takerAddress:
          description: takerAddress
          type: string
        takerFees:
          description: takerFees
          items:
            $ref: '#/components/schemas/_v1_ts_sdk_orderbook_fulfillOrder_post_request_takerFees_inner'
          type: array
        amountToFill:
          description: amountToFill
          type: string
      required:
      - listingId
      - takerAddress
      - takerFees
      type: object
    _v1_ts_sdk_orderbook_fulfillOrder_post_200_response:
      description: Response schema for the fulfillOrder endpoint
      example:
        expiration: expiration
        actions:
        - populatedTransactions:
            data: data
            accessList:
            - address: address
              storageKeys:
              - storageKeys
              - storageKeys
            - address: address
              storageKeys:
              - storageKeys
              - storageKeys
            customData:
              key: ""
            type: 1.4658129805029452
            nonce: 0.8008281904610115
            gasLimit: gasLimit
            chainId: 6.027456183070403
            maxPriorityFeePerGas: maxPriorityFeePerGas
            from: from
            to: to
            maxFeePerGas: maxFeePerGas
            value: value
            gasPrice: gasPrice
            ccipReadEnabled: true
          purpose: APPROVAL
          type: TRANSACTION
        - populatedTransactions:
            data: data
            accessList:
            - address: address
              storageKeys:
              - storageKeys
              - storageKeys
            - address: address
              storageKeys:
              - storageKeys
              - storageKeys
            customData:
              key: ""
            type: 1.4658129805029452
            nonce: 0.8008281904610115
            gasLimit: gasLimit
            chainId: 6.027456183070403
            maxPriorityFeePerGas: maxPriorityFeePerGas
            from: from
            to: to
            maxFeePerGas: maxFeePerGas
            value: value
            gasPrice: gasPrice
            ccipReadEnabled: true
          purpose: APPROVAL
          type: TRANSACTION
        order:
          chain:
            name: name
            id: id
          fees:
          - amount: amount
            recipientAddress: recipientAddress
            type: MAKER_ECOSYSTEM
          - amount: amount
            recipientAddress: recipientAddress
            type: MAKER_ECOSYSTEM
          salt: salt
          accountAddress: accountAddress
          signature: signature
          buy:
          - amount: amount
            contractAddress: contractAddress
            type: ERC20
          - amount: amount
            contractAddress: contractAddress
            type: ERC20
          sell:
          - amount: amount
            tokenId: tokenId
            contractAddress: contractAddress
            type: ERC1155
          - amount: amount
            tokenId: tokenId
            contractAddress: contractAddress
            type: ERC1155
          endAt: endAt
          type: LISTING
          createdAt: createdAt
          fillStatus:
            denominator: denominator
            numerator: numerator
          protocolData:
            seaportVersion: seaportVersion
            orderType: FULL_RESTRICTED
            counter: counter
            zoneAddress: zoneAddress
            seaportAddress: seaportAddress
          id: id
          startAt: startAt
          orderHash: orderHash
          status:
            name: ACTIVE
          updatedAt: updatedAt
      properties:
        actions:
          items:
            $ref: '#/components/schemas/TransactionAction'
          type: array
        expiration:
          description: |-
            User MUST submit the fulfillment transaction before the expiration
            Submitting after the expiration will result in a on chain revert
          type: string
        order:
          $ref: '#/components/schemas/Order'
      type: object
    _v1_ts_sdk_orderbook_prepareListing_post_request_buy:
      oneOf:
      - $ref: '#/components/schemas/ERC20Item'
      - $ref: '#/components/schemas/NativeItem'
    _v1_ts_sdk_orderbook_prepareListing_post_request_sell:
      oneOf:
      - $ref: '#/components/schemas/ERC1155Item'
      - $ref: '#/components/schemas/ERC721Item'
    _v1_ts_sdk_orderbook_prepareListing_post_request:
      properties:
        buy:
          $ref: '#/components/schemas/_v1_ts_sdk_orderbook_prepareListing_post_request_buy'
        makerAddress:
          type: string
        orderExpiry:
          format: date-time
          type: string
        sell:
          $ref: '#/components/schemas/_v1_ts_sdk_orderbook_prepareListing_post_request_sell'
      required:
      - buy
      - makerAddress
      - sell
      type: object
    _v1_ts_sdk_orderbook_prepareListing_post_200_response:
      description: Response schema for the prepareListing endpoint
      example:
        actions:
        - populatedTransactions:
            data: data
            accessList:
            - address: address
              storageKeys:
              - storageKeys
              - storageKeys
            - address: address
              storageKeys:
              - storageKeys
              - storageKeys
            customData:
              key: ""
            type: 1.4658129805029452
            nonce: 0.8008281904610115
            gasLimit: gasLimit
            chainId: 6.027456183070403
            maxPriorityFeePerGas: maxPriorityFeePerGas
            from: from
            to: to
            maxFeePerGas: maxFeePerGas
            value: value
            gasPrice: gasPrice
            ccipReadEnabled: true
          purpose: APPROVAL
          type: TRANSACTION
        - populatedTransactions:
            data: data
            accessList:
            - address: address
              storageKeys:
              - storageKeys
              - storageKeys
            - address: address
              storageKeys:
              - storageKeys
              - storageKeys
            customData:
              key: ""
            type: 1.4658129805029452
            nonce: 0.8008281904610115
            gasLimit: gasLimit
            chainId: 6.027456183070403
            maxPriorityFeePerGas: maxPriorityFeePerGas
            from: from
            to: to
            maxFeePerGas: maxFeePerGas
            value: value
            gasPrice: gasPrice
            ccipReadEnabled: true
          purpose: APPROVAL
          type: TRANSACTION
        orderComponents:
          offer:
          - itemType: null
            startAmount: startAmount
            identifierOrCriteria: identifierOrCriteria
            endAmount: endAmount
            token: token
          - itemType: null
            startAmount: startAmount
            identifierOrCriteria: identifierOrCriteria
            endAmount: endAmount
            token: token
          orderType: 6.027456183070403
          salt: salt
          zoneHash: zoneHash
          zone: zone
          conduitKey: conduitKey
          offerer: offerer
          consideration:
          - itemType: 0.8008281904610115
            startAmount: startAmount
            identifierOrCriteria: identifierOrCriteria
            recipient: recipient
            endAmount: endAmount
            token: token
          - itemType: 0.8008281904610115
            startAmount: startAmount
            identifierOrCriteria: identifierOrCriteria
            recipient: recipient
            endAmount: endAmount
            token: token
          startTime: startTime
          endTime: endTime
          totalOriginalConsiderationItems: totalOriginalConsiderationItems
          counter: counter
        orderHash: orderHash
      properties:
        actions:
          items:
            $ref: '#/components/schemas/Action'
          type: array
        orderComponents:
          $ref: '#/components/schemas/OrderComponents'
        orderHash:
          type: string
      required:
      - actions
      - orderComponents
      - orderHash
      type: object
    _v1_ts_sdk_orderbook_prepareOrderCancellations_post_request:
      properties:
        orderIds:
          items:
            type: string
          minItems: 1
          type: array
      required:
      - orderIds
      type: object
    _v1_ts_sdk_orderbook_prepareOrderCancellations_post_200_response:
      description: Response schema for the prepareOrderCancellations endpoint
      example:
        signableAction:
          purpose: CREATE_LISTING
          message:
            types:
              key:
              - name: name
                type: type
              - name: name
                type: type
            primaryType: primaryType
            domain:
              salt: salt
              chainId: chainId
              name: name
              version: version
              verifyingContract: verifyingContract
            message:
              key: ""
          type: SIGNABLE
      properties:
        signableAction:
          $ref: '#/components/schemas/SignableAction'
      type: object
    OrderComponents_consideration_inner:
      example:
        itemType: 0.8008281904610115
        startAmount: startAmount
        identifierOrCriteria: identifierOrCriteria
        recipient: recipient
        endAmount: endAmount
        token: token
      properties:
        endAmount:
          type: string
        identifierOrCriteria:
          type: string
        itemType:
          $ref: '#/components/schemas/ItemType'
        recipient:
          type: string
        startAmount:
          type: string
        token:
          type: string
      required:
      - endAmount
      - identifierOrCriteria
      - itemType
      - recipient
      - startAmount
      - token
      type: object
    OrderComponents_offer_inner:
      example:
        itemType: null
        startAmount: startAmount
        identifierOrCriteria: identifierOrCriteria
        endAmount: endAmount
        token: token
      properties:
        endAmount:
          type: string
        identifierOrCriteria:
          type: string
        itemType:
          $ref: '#/components/schemas/ItemType'
        startAmount:
          type: string
        token:
          type: string
      required:
      - endAmount
      - identifierOrCriteria
      - itemType
      - startAmount
      - token
      type: object
    RecordStringTypedDataField_value_inner:
      additionalProperties: false
      example:
        name: name
        type: type
      properties:
        name:
          type: string
        type:
          type: string
      required:
      - name
      - type
      type: object
    SignableAction_message:
      example:
        types:
          key:
          - name: name
            type: type
          - name: name
            type: type
        primaryType: primaryType
        domain:
          salt: salt
          chainId: chainId
          name: name
          version: version
          verifyingContract: verifyingContract
        message:
          key: ""
      properties:
        domain:
          $ref: '#/components/schemas/TypedDataDomain'
        types:
          additionalProperties:
            items:
              $ref: '#/components/schemas/RecordStringTypedDataField_value_inner'
            type: array
          type: object
        message:
          additionalProperties: true
          type: object
        primaryType:
          type: string
      type: object
    TransactionAction_populatedTransactions_accessList_inner:
      example:
        address: address
        storageKeys:
        - storageKeys
        - storageKeys
      properties:
        address:
          type: string
        storageKeys:
          items:
            type: string
          type: array
      type: object
    TransactionAction_populatedTransactions:
      example:
        data: data
        accessList:
        - address: address
          storageKeys:
          - storageKeys
          - storageKeys
        - address: address
          storageKeys:
          - storageKeys
          - storageKeys
        customData:
          key: ""
        type: 1.4658129805029452
        nonce: 0.8008281904610115
        gasLimit: gasLimit
        chainId: 6.027456183070403
        maxPriorityFeePerGas: maxPriorityFeePerGas
        from: from
        to: to
        maxFeePerGas: maxFeePerGas
        value: value
        gasPrice: gasPrice
        ccipReadEnabled: true
      properties:
        to:
          type: string
        from:
          type: string
        nonce:
          type: number
        gasLimit:
          type: string
        gasPrice:
          type: string
        data:
          type: string
        value:
          type: string
        chainId:
          type: number
        type:
          type: number
        accessList:
          items:
            $ref: '#/components/schemas/TransactionAction_populatedTransactions_accessList_inner'
          type: array
        maxFeePerGas:
          type: string
        maxPriorityFeePerGas:
          type: string
        customData:
          additionalProperties: true
          type: object
        ccipReadEnabled:
          type: boolean
      type: object
    Order_chain:
      example:
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
      type: object
    Order_fillStatus:
      example:
        denominator: denominator
        numerator: numerator
      properties:
        denominator:
          type: string
        numerator:
          type: string
      type: object
    Order_protocolData:
      example:
        seaportVersion: seaportVersion
        orderType: FULL_RESTRICTED
        counter: counter
        zoneAddress: zoneAddress
        seaportAddress: seaportAddress
      properties:
        counter:
          type: string
        orderType:
          enum:
          - FULL_RESTRICTED
          - PARTIAL_RESTRICTED
          type: string
        seaportAddress:
          type: string
        seaportVersion:
          type: string
        zoneAddress:
          type: string
      type: object
    OrderStatus_oneOf:
      example:
        name: ACTIVE
      properties:
        name:
          description: The order status that indicates an order can be fulfilled.
          enum:
          - ACTIVE
          type: string
      type: object
    OrderStatus_oneOf_1:
      properties:
        cancellation_type:
          $ref: '#/components/schemas/CancellationType'
        name:
          description: The order status indicating a order is has been cancelled or
            about to be cancelled.
          enum:
          - CANCELLED
          type: string
        pending:
          description: Whether the cancellation of the order is pending
          type: boolean
      type: object
    OrderStatus_oneOf_2:
      properties:
        name:
          description: A terminal order status indicating that an order cannot be
            fulfilled due to expiry.
          enum:
          - EXPIRED
          type: string
      type: object
    OrderStatus_oneOf_3:
      properties:
        name:
          description: A terminal order status indicating that an order has been fulfilled.
          enum:
          - FILLED
          type: string
      type: object
    OrderStatus_oneOf_4:
      properties:
        name:
          description: The order status that indicates an order cannot be fulfilled.
          enum:
          - INACTIVE
          type: string
        sufficient_approvals:
          description: Whether the order offerer has sufficient approvals
          type: boolean
        sufficient_balances:
          description: Whether the order offerer still has sufficient balance to complete
            the order
          type: boolean
      type: object
    OrderStatus_oneOf_5:
      properties:
        evaluated:
          description: Whether the order has been evaluated after its creation
          type: boolean
        name:
          description: The order status that indicates the order is yet to be active
            due to various reasons.
          enum:
          - PENDING
          type: string
        started:
          description: Whether the order has reached its specified start time
          type: boolean
      type: object

